name: Package and Create Artifact

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    branches: [ master ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-package:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get latest tag
        id: get-version
        run: |
          $latestTag = git describe --tags --abbrev=0
          if ($latestTag) {
            $version = $latestTag -replace '^v', ''
            echo "version=$version" >> $env:GITHUB_OUTPUT
            echo "tag=$latestTag" >> $env:GITHUB_OUTPUT
            echo "Found version: $version from tag: $latestTag"
          } else {
            # Fallback
            $version = "1.0.0"
            echo "version=$version" >> $env:GITHUB_OUTPUT
            echo "tag=v$version" >> $env:GITHUB_OUTPUT
            echo "No tags found, using default version: $version"
          }

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install WIX toolset
        run: |
          Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
          Start-Process -FilePath ".\wix311.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Run clean build with Maven
        run: mvn clean package

      - name: Project version
        run: echo "Building version ${{ steps.get-version.outputs.version }} from tag ${{ steps.get-version.outputs.tag }}"

      - name: List target directory contents (for debugging)
        run: |
          echo "Contents of target directory:"
          Get-ChildItem -Path target/ -Recurse | Format-Table Name, FullName
          echo "Looking for JAR files specifically:"
          Get-ChildItem -Path target/ -Filter "*.jar" | Format-Table Name, FullName

      - name: Create package directory
        run: mkdir -p target/package

      - name: Find the main JAR file
        id: find-jar
        run: |
          $jarFile = Get-ChildItem -Path target/ -Filter "*infirmary-application*.jar" | Where-Object { $_.Name -notlike "*-sources.jar" -and $_.Name -notlike "*-javadoc.jar" } | Select-Object -First 1
          if ($jarFile) {
            echo "jar-name=$($jarFile.Name)" >> $env:GITHUB_OUTPUT
            echo "Found JAR: $($jarFile.Name)"
          } else {
            echo "No suitable JAR file found! Available JARs:"
            Get-ChildItem -Path target/ -Filter "*.jar" | ForEach-Object { echo $_.Name }
            exit 1
          }

      - name: Create JavaFX application installer artifact
        run: |
          jpackage --input target/package `
            --name InfirmaryApplication `
            --main-jar "${{ steps.find-jar.outputs.jar-name }}" `
            --type exe `
            --dest target/package `
            --win-menu `
            --win-shortcut `
            --module-path "target/lib" `
            --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base `
            --app-version "${{ steps.get-version.outputs.version }}" `
            --vendor "RoCS" `
            --description "Infirmary Desktop Application" `
            --win-dir-chooser `
            --verbose

      - name: Upload the installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: InfirmaryApplication-Installer-${{ steps.get-version.outputs.version }}
          path: target/package/InfirmaryApplication-*.exe

      - name: Upload installer to release
        if: github.event_name == 'workflow_run'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-version.outputs.tag }}
          files: target/package/InfirmaryApplication-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}